package de.daedo.mixin.base;

/**
 * The {@link IMixinSupport} interface is the basic interface 
 * to be implemented by any class that wants to support {@link Mixin}s.
 */
public interface IMixinSupport {
	/**
	 * Returns an instance of any given {@link Mixin}, 
	 * If the mixin has not yet been created it is generated by calling 
	 * the empty constructor via reflection. 
	 * 
	 * @param <M> The type of {@link Mixin}
	 * @param clazz the mixin class, may not be null
	 * @return the {@link Mixin}, never returns null
	 * @throws NullPointerException should clazz be null
	 * @throws UnsupportedOperationException if it cannot instantiate a given {@link Mixin}
	 */
	<M extends Mixin> M getMixin(Class<M> clazz);
}
